-- MySQL Script generated by MySQL Workbench
-- 09/08/16 15:43:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Transporter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Transporter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Transporter` DEFAULT CHARACTER SET utf8 ;
USE `Transporter` ;

-- -----------------------------------------------------
-- Table `Transporter`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporter`.`Roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transporter`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporter`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `passport` VARCHAR(200) NULL,
  `idRole` INT NOT NULL,
  `isBlocked` TINYINT(1) NOT NULL,
  `photoURL` VARCHAR(200) NULL,
  `phone` VARCHAR(200) NOT NULL,
  `rate` DOUBLE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `idRole_idx` (`idRole` ASC),
  CONSTRAINT `idRole`
    FOREIGN KEY (`idRole`)
    REFERENCES `Transporter`.`Roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transporter`.`Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporter`.`Cars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `height` DOUBLE NOT NULL,
  `width` DOUBLE NOT NULL,
  `length` DOUBLE NOT NULL,
  `weight` DOUBLE NOT NULL,
  `dokuments` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transporter`.`UserCars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporter`.`UserCars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUsers` INT NOT NULL,
  `idCars` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `idUser_idx` (`idUsers` ASC),
  INDEX `idCars_idx` (`idCars` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUsers`)
    REFERENCES `Transporter`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCars`
    FOREIGN KEY (`idCars`)
    REFERENCES `Transporter`.`Cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transporter`.`Regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporter`.`Regions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transporter`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporter`.`Cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `idRegion` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `idRegion_idx` (`idRegion` ASC),
  CONSTRAINT `idRegion`
    FOREIGN KEY (`idRegion`)
    REFERENCES `Transporter`.`Regions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transporter`.`Routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporter`.`Routes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idFrom` INT NOT NULL,
  `idTo` INT NOT NULL,
  `idCar` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `durations` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `idFrom_idx` (`idFrom` ASC),
  INDEX `idTo_idx` (`idTo` ASC),
  INDEX `idCar_idx` (`idCar` ASC),
  CONSTRAINT `idFrom`
    FOREIGN KEY (`idFrom`)
    REFERENCES `Transporter`.`Cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTo`
    FOREIGN KEY (`idTo`)
    REFERENCES `Transporter`.`Cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCar`
    FOREIGN KEY (`idCar`)
    REFERENCES `Transporter`.`Cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transporter`.`RouteCities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporter`.`RouteCities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idRoute` INT NOT NULL,
  `idCity` INT NOT NULL,
  `visited` TINYINT(1) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `idRoute_idx` (`idRoute` ASC),
  INDEX `idCity_idx` (`idCity` ASC),
  CONSTRAINT `idRoute`
    FOREIGN KEY (`idRoute`)
    REFERENCES `Transporter`.`Routes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCity`
    FOREIGN KEY (`idCity`)
    REFERENCES `Transporter`.`Cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transporter`.`OrderStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporter`.`OrderStatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `status_UNIQUE` (`status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transporter`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporter`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idStatus` INT NOT NULL,
  `idRoute` INT NULL,
  `idFrom` INT NULL,
  `idTo` INT NULL,
  `height` DOUBLE NOT NULL,
  `width` DOUBLE NOT NULL,
  `length` DOUBLE NOT NULL,
  `weight` DOUBLE NOT NULL,
  `price` DOUBLE NOT NULL,
  `startTime` DATE NOT NULL,
  `endTime` DATE NOT NULL,
  `description` VARCHAR(1000) NULL,
  `photoURL` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `idUser_idx` (`idUser` ASC),
  INDEX `idStatus_idx` (`idStatus` ASC),
  INDEX `idRouter_idx` (`idRoute` ASC),
  INDEX `idTo_idx` (`idTo` ASC),
  INDEX `idFrom_idx` (`idFrom` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `Transporter`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idStatus`
    FOREIGN KEY (`idStatus`)
    REFERENCES `Transporter`.`OrderStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idRoute`
    FOREIGN KEY (`idRoute`)
    REFERENCES `Transporter`.`Routes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idFrom`
    FOREIGN KEY (`idFrom`)
    REFERENCES `Transporter`.`Cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTo`
    FOREIGN KEY (`idTo`)
    REFERENCES `Transporter`.`Cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transporter`.`Feedbacks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporter`.`Feedbacks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `idOrder` INT NOT NULL,
  `text` VARCHAR(1000) NULL,
  `rate` INT NOT NULL,
  `isApproved` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `idUser_idx` (`idUser` ASC),
  INDEX `idOrder_idx` (`idOrder` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `Transporter`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idOrder`
    FOREIGN KEY (`idOrder`)
    REFERENCES `Transporter`.`Orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
